### ISSUE TITLE
error on installing lib_resume_builder_AIHawk

### ISSUE THREAD

**Issue by gschwenz** [feder-cr/resume_render_from_job_description#4]
Hello,

I ran the project once, and it errored out on installing the library lib_resume_builder_AIHawk and then i read through the terminal output and attempted to install it very a terminal line
`python -m pip install git+https://github.com/feder-cr/lib_resume_builder_AIHawk.git`
This also errored out:
`Collecting git+https://github.com/feder-cr/lib_resume_builder_AIHawk.git
  Cloning https://github.com/feder-cr/lib_resume_builder_AIHawk.git to /tmp/pip-req-build-bkye7xcy
  Running command git clone --filter=blob:none --quiet https://github.com/feder-cr/lib_resume_builder_AIHawk.git /tmp/pip-req-build-bkye7xcy
  Resolved https://github.com/feder-cr/lib_resume_builder_AIHawk.git to commit d1cab8131...
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "./resume_render_from_job_description/venv-resume/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "./resume_render_from_job_description/venv-resume/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "./resume_render_from_job_description/venv-resume/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-guyhm90m/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-guyhm90m/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-guyhm90m/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 502, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-guyhm90m/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

Would be very appreciative of any insight on how to get this running, thanks!

**Comment by dmartin4820** [comment]
Related [error on pip install](https://github.com/feder-cr/linkedIn_auto_jobs_applier_with_AI/issues/65)
